home:
    path: /
    controller: App\Controller\LoginController::index
    methods: [GET, POST]

dashboard:
    path: /dashboard
    controller: App\Controller\HomeController::index
    methods: [GET]

player_classes:
    path: /player-classes
    controller: App\Controller\PlayerClassesController::index
    methods: [GET]

armor_types:
    path: /armor-types
    controller: App\Controller\PlayerClassesController::index
    methods: [GET]

weapon_types:
    path: /weapon-types
    controller: App\Controller\PlayerClassesController::index
    methods: [GET]